### ISSUE TITLE
lighting field preview window error

### ISSUE THREAD

**Issue by AlexNorth365** [regcs/AliceLG#114]
**Describe the bug**
On blender3.5, install the latest Alice plug-in, when switching the language option on blender, in a non-English environment, click the lighting field preview window, there will be an abnormal pop-up window reporting an error.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform & Versions (please complete the following information):**
 - OS: macOS
 - Blender Version: 3.5
 - Alice/LG Version：2.2

**Attach log files**
Head over to Blender's addon directory ([Don't know where this is?](https://docs.blender.org/manual/en/latest/advanced/blender_directory_layout.html)), in that directory go to '/AliceLG/logs/', and attach the `pylightio.log` and `alice-lg.log` here:

**Comment by AlexNorth365** [comment]
Python: --- Logging error ---
Traceback (most recent call last):
  File "/Applications/Blender3.5.app/Contents/Resources/3.5/python/lib/python3.10/logging/handlers.py", line 74, in emit
    self.doRollover()
  File "/Applications/Blender3.5.app/Contents/Resources/3.5/python/lib/python3.10/logging/handlers.py", line 433, in doRollover
    if os.path.exists(dfn):
  File "/Applications/Blender3.5.app/Contents/Resources/3.5/python/lib/python3.10/genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
Call stack:
  File "/Users/cdy/Library/Application Support/Blender/3.5/scripts/addons/AliceLG/__init__.py", line 78, in log_exhook
    LookingGlassAddonLogger.critical("An unhandled error occured. Here is the traceback:\n", exc_info=(exc_type, exc_value, exc_traceback))
Message: 'An unhandled error occured. Here is the traceback:\n'
Arguments: ()
Traceback (most recent call last):
  File "/Users/cdy/Library/Application Support/Blender/3.5/scripts/addons/AliceLG/lightfield_render.py", line 1466, in invoke
    self.render_settings = RenderSettings(bpy.context.scene, self.animation, self.use_lockfile, self.use_multiview, self.blocking)
  File "/Users/cdy/Library/Application Support/Blender/3.5/scripts/addons/AliceLG/lightfield_render.py", line 1015, in __init__
    self.original = self.copy()
  File "/Users/cdy/Library/Application Support/Blender/3.5/scripts/addons/AliceLG/lightfield_render.py", line 1305, in copy
    return self.to_dict(self)
  File "/Users/cdy/Library/Application Support/Blender/3.5/scripts/addons/AliceLG/lightfield_render.py", line 1141, in to_dict
    data = dict([(key, self.to_dict(value, classkey))
  File "/Users/cdy/Library/Application Support/Blender/3.5/scripts/addons/AliceLG/lightfield_render.py", line 1141, in <listcomp>
    data = dict([(key, self.to_dict(value, classkey))
  File "/Users/cdy/Library/Application Support/Blender/3.5/scripts/addons/AliceLG/lightfield_render.py", line 1114, in to_dict
    if not callable(getattr(obj, key)) and not key.startswith('_'):
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 3: invalid start byte

**Comment by AlexNorth365** [comment]
[
<img width="809" alt="Screen2023-05-15 22 04 21" src="https://github.com/regcs/AliceLG/assets/1666157/f52e24af-2e96-435e-8c43-ccc69edd3ddd">
](url)

**Comment by regcs** [comment]
Hi, thanks for the bug report. What language did you change to?

**Comment by Philmist** [comment]
I have same problem.

To reproduce:

1.  Change blender's interface language to Japanese.
2.  Install AliceLG.
3.  Install dependency and restart blender.
4.  Convert camera for LKG.
5.  Turn on Lightfield window, then blender outputs this error.
![image](https://github.com/regcs/AliceLG/assets/431640/33dcebcb-d1c1-4adb-b906-254d920c5b98)

However, the following procedure works correctly.

1.  Change blender's interface language to English.
2.  Install AliceLG
3.  Install dependency and restart blender.
4.  Change language to Japanese.
5.  Turn on Lightfield window.

But if I restart Blender with the UI language set to Japanese and activate the Lightfield window, the same error reappears.

**Comment by AlexNorth365** [comment]
Dear there, I am in a similar situation and changing the settings to Chinese or another non-English language will reproduce this phenomenon.

**Comment by AlexNorth365** [comment]
This problem, which is easy to repeat and will come up every time, is looking forward to your free time and being able to take a look. Thank you very much.

**Comment by regcs** [comment]
@AlexNorth365: Sorry for the late response. The "free time" was and is the current issue. ;) I will try to have a closer look in the next days.

**Comment by regcs** [comment]
Fixed by @Philmist. Thanks a lot!
