### ISSUE TITLE
Does not work on Mac OS Ventura on M2

### ISSUE THREAD

**Issue by orcinus** [regcs/AliceLG#120]
Initial attempt to install the add-on seemingly worked, but produced pynng build errors when trying to connect to the service. After reinstalling Blender and the add-on, installing dependencies started failing. After updating addon folder pip3, it finally completed without an error, but now the add-on init fails.

Here's the log:

```
[Alice/LG] [CRITICAL] 10/02/2023 00:58:47 - An unhandled error occured. Here is the traceback:
Traceback (most recent call last):
  File "/Users/ante/Library/Application Support/Blender/2.93/scripts/addons/AliceLG/__init__.py", line 212, in <module>
    importlib.reload(preferences)
NameError: name 'preferences' is not defined

During handling of the above exception, another exception occurred:

RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
Traceback (most recent call last):
  File "/Users/ante/Library/Application Support/Blender/2.93/scripts/addons/AliceLG/__init__.py", line 212, in <module>
    importlib.reload(preferences)
NameError: name 'preferences' is not defined

During handling of the above exception, another exception occurred:

RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
Traceback (most recent call last):
  File "/Users/ante/Library/Application Support/Blender/2.93/scripts/addons/AliceLG/__init__.py", line 212, in <module>
    importlib.reload(preferences)
NameError: name 'preferences' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/2.93/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/Users/ante/Library/Application Support/Blender/2.93/scripts/addons/AliceLG/__init__.py", line 227, in <module>
    from .lightfield_viewport import *
  File "/Users/ante/Library/Application Support/Blender/2.93/scripts/addons/AliceLG/lightfield_viewport.py", line 46, in <module>
    import pylightio as pylio
  File "/Users/ante/Library/Application Support/Blender/2.93/scripts/addons/AliceLG/lib/pylightio/__init__.py", line 33, in <module>
    from pylightio.lookingglass import *
  File "/Users/ante/Library/Application Support/Blender/2.93/scripts/addons/AliceLG/lib/pylightio/lookingglass/__init__.py", line 20, in <module>
    from pylightio.lookingglass.services import *
  File "/Users/ante/Library/Application Support/Blender/2.93/scripts/addons/AliceLG/lib/pylightio/lookingglass/services.py", line 22, in <module>
    import pynng, cv2
  File "/Users/ante/Library/Application Support/Blender/2.93/scripts/addons/AliceLG/lib/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/Users/ante/Library/Application Support/Blender/2.93/scripts/addons/AliceLG/lib/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: numpy.core.multiarray failed to import
```

**Platform & Versions (please complete the following information):**
 - OS: Mac OS X 13.5.1
 - Blender Version: 2.93.18
 - Alice/LG Version: latest release

Any help would be appreciated.

**Comment by BryanChrisBrown** [comment]
@orcinus can you try restarting blender and reinstalling the add-on?

**Comment by orcinus** [comment]
> @orcinus can you try restarting blender and reinstalling the add-on?

I did, same thing. Also tried reinstalling blender, restarting, reinstalling add-on, restarting; and a lot of other things including manually updating/uninstalling/installing numpy into the add-ons folder.
I'm out of ideas... I've got a nagging suspicion this is some weird homebrew/Ventura/M2 mess.

**Comment by regcs** [comment]
I don’t think it’s a particular M2/Ventura issue. I have it installed on a M2. 

Is there a particular reason you are using Blender 2.93? Did you also try a newer version like 3.6? 🤔

**Comment by orcinus** [comment]
I was on 2.92 because of some 3.x bugs/behavior changes, and 2.93 LTS was the lowest version (nominally) supported by the add-on. I'll give something newer a try i guess.

**Comment by regcs** [comment]
Yeah, technically it should work on >2.93.6. I just want to make sure it is not a systemic issue on your specific machine/configuration.

**Comment by regcs** [comment]
Since this issue has been silent, I will close it. Please re-open, if the issue persists.

**Comment by orcinus** [comment]
I switched back to my windows desktop in the meantime, so honestly haven't tested further.
